---
title: "Read Files Test"
author: "Michael Schmidt"
date: "1/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(raster)
library(tidyverse)
library(sf)
```

# Get .las file name from tile file name functions

## Tile names
Gets folder and returns a list of whole file names. 
```{r}
tile_paths<-list.files('imagery_files', pattern = ".tif", full.names = T)
```


## Return las name from tile name
takes in tile name and reads the corresponding .las file. 
```{r}
las_folder<-"las_files"
name_parts<-tile_paths[1]%>%
  basename()%>%
  str_split(pattern="_")

list.files(las_folder, 
           pattern = paste(name_parts[[1]][1], name_parts[[1]][2], name_parts[[1]][3], sep = "_"), 
           ignore.case = T)

?list.files
```

## lfn test function
```{r}
source("R/load_funcs.R")

tile_paths<-list.files('imagery_files', pattern = ".tif", full.names = T)

list_las<-lapply(tile_paths, lfn, "las_files")
```

## test heights with lfn test
This Test Was successful. 
```{r}
source("R/load_funcs.R")
tile_paths<-list.files('imagery_files', pattern = ".tif", full.names = T)
rasters<-lapply(tile_paths[2:3], add_heights, "las_files")
```





# Get list of training files
```{r}
tiles<-st_read("shapefiles/SanMiguel_West.shp")%>%
  select(NAME, Acres)
train_polys<-st_read("shapefiles/training_polygons12N_12102018.shp")

st_join(train_polys, tiles)%>%
  as_tibble()%>%
  distinct(NAME)%>%
  pull(NAME)
```


## Test Created Function
```{r}
list_of_tiles<-l_train_f("shapefiles/training_polygons12N_12102018.shp", "shapefiles/SanMiguel_West.shp")

lapply(list_of_tiles, lfn, "../DATA/SanMiguel_West_LAS")
```


# Write CSV test

```{r}
t<-tibble(
  header1 = "another row3", 
  header2 = "another row4"
)

write_csv(t, "delete.csv", append = TRUE)
```




