---
title: "Split Data"
author: "Michael Schmidt"
date: "1/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(caret)
options(scipen=999)
```


```{r}
source("R/load_funcs.R")
options(scipen=999)
data<-readRDS("DATA/training_data/training_data_01232020.rds")%>%
  drop_na()%>%
  mutate(class = case_when(
    class %in% c(7,2) ~ 7, #Sage and Black Sage 
    class %in% c(4,5) ~ 5, #Other_veg and other_shrub,
    class == 6 ~ 6, # PJ
    class == 1 ~ 1, # BG_rock
    class == 3 ~ 3 #Grass
  ))



trainIndex<-createDataPartition(data$class, p = .8, list = FALSE, times = 1)

data_train<-data[trainIndex, ]
data_test<-data[-trainIndex, ]
```


```{r}
library(doParallel)

no_cores<-detectCores()-2
registerDoParallel(cores=no_cores)

cl<-makeCluster(no_cores)

control <- trainControl(method = "repeatedcv", 
                     number = 10, 
                     repeats = 3, 
                     sampling="down"
                     )

mtry<-c(2,4)
tunegrid <-expand.grid(.mtry = mtry)

caret_fit_base<-train(as.factor(class)~ . , 
                  data=data_train,
                  method="rf",
                  metric="Accuracy",
                  preProcess = c("scale", "center"),
                  ntree=1000,
                  trControl=control, 
                  importance = TRUE, 
                  tuneGrid = tunegrid, 
                  verbose = TRUE,
                  allowParallel = TRUE
                  )

stopCluster(cl)

caret_fit_base


varImp(caret_fit_base)

prediction<-bind_cols(data_test, predict = predict(caret_fit_base, data_test))

caret::confusionMatrix(as.factor(prediction$class), prediction$predict)

prop.table(caret::confusionMatrix(as.factor(prediction$class), prediction$predict)$table, 2)


saveRDS(caret_fit_base, "model_runs/combined_vars/combined_vars.rds")

```


## Make prediction
```{r}

predict_raster<-brick("DATA/SanMiguel_West_heights_added/height_add_SM_GypsumGapNW_0103_180611.tif")
names(predict_raster)<-c("band1", "band2", "band3", "band4", "height")

predicted_raster<-raster::predict( predict_raster, caret_fit_base)

writeRaster(predicted_raster, "model_runs/base_model/SM_GypsumGapNW_0103_180611_PREDICTED.tif")
```


##XGboost
```{r}
data<-readRDS("DATA/training_data/training_data_01232020.rds")%>%
  drop_na()%>%
  mutate(class = case_when(
    class %in% c(7,2) ~ "Sage", #Sage and Black Sage 
    class %in% c(4,5) ~ "Other_veg", #Other_veg and other_shrub,
    class == 6 ~ "PJ", # PJ
    class == 1 ~ "BG_rock", # BG_rock
    class == 3 ~ "Grass" #Grass
  ))

trainIndex<-createDataPartition(data$class, p = .8, list = FALSE, times = 1)

data_train<-data[trainIndex, ]
data_test<-data[-trainIndex, ]

library(doParallel)

no_cores<-detectCores()-2
registerDoParallel(cores=no_cores)

cl<-makeCluster(no_cores)

ControlParamteres <- trainControl(method = "repeatedcv",
                                  number = 10,
                                  repeats = 5,
                                  savePredictions = TRUE,
                                  classProbs = TRUE,
                                  sampling="down"
)

##nrounds <- 1000

parametersGrid <-  expand.grid(eta = 0.5, 
                            colsample_bytree=0.7,
                            max_depth=5,
                            nrounds=2000,
                            gamma=0,
                            min_child_weight=1,
                            subsample = 1
                            )


modelxgboost <- train(class~ . , 
                  data=data_train,
                  method = "xgbTree",
                  trControl = ControlParamteres,
                  tuneGrid=parametersGrid,
                  allowParallel = TRUE,
                  verbose = TRUE)

stopCluster(cl)

varImp(modelxgboost)

saveRDS(modelxgboost, "model_runs/xgboost2/xgboost2.rds")

modelxgboost

prediction<-bind_cols(data_test, predict = predict(modelxgboost, data_test))

caret::confusionMatrix(as.factor(prediction$class), prediction$predict)

prop.table(caret::confusionMatrix(as.factor(prediction$class), prediction$predict)$table, 2)


```



## Make Prediction
```{r}
model<-readRDS("model_runs/xgboost2/xgboost2.rds")

raster_to_predict<-brick("DATA/SanMiguel_West_heights_added/height_add_SM_GypsumGapNW_0103_180611.tif")

names(raster_to_predict)<-c("band1", "band2", "band3", "band4", "height")
beginCluster(6)

prediction<-clusterR(raster_to_predict, predict, args = list(model))


endCluster()
prediction<-raster::predict(raster, model)

writeRaster(prediction, "model_runs/xgboost2/GypsumGapNW_0103_180611.tif")

```


USE 
```{r}
library(CAST)
library(doParallel)
library(caret)
data<-readRDS("DATA/training_data/training_polygons12N_02122020_BS_UPDATE2_normalized.rds")%>%
  drop_na()%>%
  mutate(Class = case_when(
    Class %in% c(7,2) ~ "Sage", #Sage and Black Sage 
    Class %in% c(4,5) ~ "Other_veg", #Other_veg and other_shrub,
    Class == 6 ~ "PJ", # PJ
    Class == 1 ~ "BG_rock", # BG_rock
    Class == 3 ~ "Grass" #Grass
  ),
  height = round(height, digits = 1))

trainIndex<-createDataPartition(data$Class, p = .8, list = FALSE, times = 1)

data_train<-data[trainIndex, ]
data_test<-data[-trainIndex, ]

indeces<-CreateSpacetimeFolds(data_train, spacevar = "Id", k = 10)

##indeces$index



control <- trainControl(method = "cv",
                        number = 10,
                        sampling="down",
                        index = indeces$index
                     )

mtry<-c(2:5)
tunegrid <-expand.grid(.mtry = mtry)

no_cores<-detectCores()-4
cl<-makePSOCKcluster(no_cores)
registerDoParallel(cl)

start_time<-Sys.time()
caret_fit_base<-train(as.factor(Class) ~ . , 
                  data=select(data_train, -Id),
                  method="rf",
                  trControl=control,
                  tuneGrid=tunegrid,
                  metric= "Accuracy"
                  )
end_time<-Sys.time()

start_time-end_time

stopCluster(cl)

caret_fit_base

prediction<-bind_cols(data_test, predict = predict(caret_fit_base, data_test))

prop.table(caret::confusionMatrix(as.factor(prediction$Class), prediction$predict)$table, 2)

saveRDS(caret_fit_base, "model_runs/ID_CV_model_BS_UPDATE_normalized/ID_CV_model_BS_UPDATE3_normalized.rds")


```


## Predict the above model
```{r}
library(raster)
library(caret)
s
```


